#!/usr/bin/env python3
"""Generate the `docs/reference/` files from source.

    python docs/reference/generate.py          # rewrite every reference file
    python docs/reference/generate.py --check  # exit 1 if any committed file drifted

Every fact in the files this writes is read from code at generation time —
the state schema, the argparse trees, the gate registry and its constants,
the status vocabulary, and the MCP server's tool list. Nothing is typed by
hand except the headings and the one-line orientation under each.
`tests/test_reference_docs.py` runs `--check` logic in CI, so a code change
that is not regenerated here fails the build instead of misleading a reader.
"""
from __future__ import annotations

import argparse
import inspect
import json
import sys
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parents[2]
BIN = ROOT / "bin"
OUT = ROOT / "docs" / "reference"

for _p in (str(ROOT), str(BIN)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

GENERATED_NOTE = (
    "> Generated by `docs/reference/generate.py` from source. Do not edit by hand —\n"
    "> change the code, then run `python docs/reference/generate.py`. CI fails when\n"
    "> this file and the code disagree.\n"
)


# ── helpers ────────────────────────────────────────────────────────────────


def _cell(text: Any) -> str:
    """One markdown table cell: single line, pipes escaped."""
    s = "" if text is None else str(text)
    s = " ".join(s.split())
    return s.replace("|", "\\|")


def _first_paragraph(doc: str | None) -> str:
    if not doc:
        return ""
    return " ".join(inspect.cleandoc(doc).split("\n\n")[0].split())


def _json_type(node: dict) -> str:
    t = node.get("type")
    if isinstance(t, list):
        return " \\| ".join(t)
    if t:
        return str(t)
    if "enum" in node:
        return "enum"
    return "any"


class _Captured(Exception):
    def __init__(self, parser: argparse.ArgumentParser) -> None:
        super().__init__("parser captured")
        self.parser = parser


def _capture_parser(call: Callable[[], Any]) -> argparse.ArgumentParser:
    """Run `call` until its first `parse_args` and return that parser — so a
    CLI whose parser is built inside `main()` is documented from the parser
    object itself, never from version-dependent `--help` text."""
    original = argparse.ArgumentParser.parse_args

    def _grab(self, *args, **kwargs):  # noqa: ANN001
        raise _Captured(self)

    argparse.ArgumentParser.parse_args = _grab  # type: ignore[assignment]
    try:
        call()
    except _Captured as captured:
        return captured.parser
    finally:
        argparse.ArgumentParser.parse_args = original  # type: ignore[assignment]
    raise RuntimeError("the call returned without parsing arguments")


def _arg_rows(parser: argparse.ArgumentParser) -> list[str]:
    rows = []
    for action in parser._actions:  # noqa: SLF001 — argparse exposes no public iterator
        if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction)):  # noqa: SLF001
            continue
        name = ", ".join(action.option_strings) if action.option_strings else action.dest
        if action.option_strings:
            required = "yes" if action.required else "no"
        else:
            required = "no" if action.nargs in ("?", "*", argparse.REMAINDER) else "yes"
        extra = []
        if action.choices:
            extra.append("choices: " + ", ".join(f"`{c}`" for c in action.choices))
        if action.nargs not in (None, 0):
            extra.append(f"nargs `{action.nargs}`")
        if action.default not in (None, argparse.SUPPRESS, [], False) and action.option_strings:
            extra.append(f"default `{action.default}`")
        help_text = action.help or ""
        if extra:
            help_text = (help_text + " — " if help_text else "") + "; ".join(extra)
        rows.append(f"| `{name}` | {required} | {_cell(help_text)} |")
    return rows


def _render_parser(title: str, invocation: str, parser: argparse.ArgumentParser, lines: list[str]) -> None:
    lines.append(f"## {title}")
    lines.append("")
    lines.append(f"`{invocation}`")
    if parser.description:
        lines.append("")
        lines.append(_cell(parser.description))
    rows = _arg_rows(parser)
    if rows:
        lines += ["", "| Argument | Required | Notes |", "|---|---|---|", *rows]
    subparsers = [a for a in parser._actions if isinstance(a, argparse._SubParsersAction)]  # noqa: SLF001
    for sub in subparsers:
        helps = {choice.dest: choice.help for choice in sub._choices_actions}  # noqa: SLF001
        for name, child in sub.choices.items():
            lines.append("")
            lines.append(f"### `{name}`")
            lines.append("")
            if helps.get(name):
                lines.append(_cell(helps[name]))
                lines.append("")
            child_rows = _arg_rows(child)
            if child_rows:
                lines += ["| Argument | Required | Notes |", "|---|---|---|", *child_rows]
            else:
                lines.append("No arguments.")
    lines.append("")


# ── state-fields.md ────────────────────────────────────────────────────────


def _schema_rows(props: dict, required: list[str], prefix: str, rows: list[str], nested: list[tuple]) -> None:
    for name, node in props.items():
        field = f"{prefix}{name}"
        rows.append(
            f"| `{field}` | {_json_type(node)} | {'yes' if name in required else 'no'} | "
            f"{_cell(node.get('description', ''))}"
            + (" Values: " + ", ".join(f"`{'null' if v is None else v}`" for v in node["enum"]) + "." if "enum" in node else "")
            + " |"
        )
        if isinstance(node.get("properties"), dict):
            nested.append((field, node["properties"], node.get("required", [])))
        items = node.get("items")
        if isinstance(items, dict) and isinstance(items.get("properties"), dict):
            nested.append((f"{field}[]", items["properties"], items.get("required", [])))


def render_state_fields() -> str:
    schema = json.loads((BIN / "loop_state.schema.json").read_text(encoding="utf-8"))
    lines = [
        "# Reference — `loop.state.json` fields",
        "",
        GENERATED_NOTE,
        "Source: `bin/loop_state.schema.json`. Every field below is written only by the event verbs in",
        "`bin/loop_state.py` (see [`cli.md`](cli.md)); never edit the state file by hand.",
        "",
        f"**Schema:** `{schema.get('$id', '')}`",
        "",
        "## Top-level fields",
        "",
        "| Field | Type | Required | Description |",
        "|---|---|---|---|",
    ]
    rows: list[str] = []
    nested: list[tuple] = []
    _schema_rows(schema["properties"], schema.get("required", []), "", rows, nested)
    lines += rows
    while nested:
        field, props, required = nested.pop(0)
        lines += ["", f"## `{field}`", "", "| Field | Type | Required | Description |", "|---|---|---|---|"]
        sub_rows: list[str] = []
        _schema_rows(props, required, f"{field}.", sub_rows, nested)
        lines += sub_rows
    lines.append("")
    return "\n".join(lines)


# ── cli.md ─────────────────────────────────────────────────────────────────


def render_cli() -> str:
    import drive_map
    import loop_state
    import plan_lint
    import validate_candidate
    from hyperspace import cli as hs_cli

    lines = [
        "# Reference — command-line interfaces",
        "",
        GENERATED_NOTE,
        "Two command surfaces. The **engine scripts** in `bin/` run the loop; inside a session the skills",
        "call them as `.hyperspace/env/bin/python \"${CLAUDE_PLUGIN_ROOT}/bin/<script>.py\" …`. The",
        "**`hyperspace` command** is installed into the project's `.hyperspace/env` by the setup skill and",
        "runs the store, the local web server and the health check.",
        "",
    ]
    _render_parser("`bin/loop_state.py` — the run-state machine", "loop_state.py <command> …", loop_state.build_parser(), lines)
    _render_parser("`bin/drive_map.py` — the run folder's generated map", "drive_map.py <command> <run_dir>",
                   _capture_parser(lambda: drive_map.main([])), lines)
    _render_parser("`bin/plan_lint.py` — plan self-check (not a gate)", "plan_lint.py …", plan_lint._parser(), lines)

    lines += [
        "## `bin/validate_candidate.py` — pre-gate contract check",
        "",
        "`validate_candidate.py <tests.json>`",
        "",
        _cell(_first_paragraph(validate_candidate.__doc__)),
        "",
        "| Exit | Meaning |",
        "|---|---|",
        "| `0` | Prints `VALID <path>`. |",
        "| `1` | Prints `INVALID <path>` and the validator's message. |",
        "| `2` | Usage, an unreadable file, or the contract could not load. |",
        "",
        "## `hyperspace` — the store, the web server, the health check",
        "",
        "`hyperspace <command> …` · `hyperspace --version`",
        "",
    ]
    for name, fn in hs_cli.SUBCOMMANDS.items():
        parser = _capture_parser(lambda fn=fn: fn(argparse.Namespace(rest=[], command=name)))
        lines.append(f"### `hyperspace {name}`")
        lines.append("")
        summary = _first_paragraph(fn.__doc__)
        if summary:
            lines.append(_cell(summary))
            lines.append("")
        rows = _arg_rows(parser)
        if rows:
            lines += ["| Argument | Required | Notes |", "|---|---|---|", *rows, ""]
    return "\n".join(lines).rstrip("\n") + "\n"


# ── gate-contracts.md ──────────────────────────────────────────────────────


def render_gate_contracts() -> str:
    import loop_state
    import node_gates

    parser = loop_state.build_parser()
    gate_pass = next(
        a for a in parser._actions if isinstance(a, argparse._SubParsersAction)  # noqa: SLF001
    ).choices["gate-pass"]
    flags_by_node: dict[str, list[str]] = {}
    optional_flags: list[str] = []
    for action in gate_pass._actions:  # noqa: SLF001
        help_text = action.help or ""
        if not action.option_strings or action.option_strings[0] in ("-h", "--node", "--by", "--artifact"):
            continue
        marker = "required when --node "
        if marker in help_text:
            node = help_text.split(marker, 1)[1].split()[0].strip(".,;)")
            flags_by_node.setdefault(node, []).append(action.option_strings[0])
        else:
            optional_flags.append(action.option_strings[0])

    lines = [
        "# Reference — gate contracts",
        "",
        GENERATED_NOTE,
        "Source: `CHECKS` in `bin/node_gates.py` and the `gate-pass` argument tree in `bin/loop_state.py`.",
        "Only the nodes below have an exit check; `gate-pass` refuses any other `--node` with exit 2.",
        "",
        "## Registered checks",
        "",
        "| Node | Check | Required evidence flags | Optional flags |",
        "|---|---|---|---|",
    ]
    for node, fn in node_gates.CHECKS.items():
        required = ", ".join(f"`{f}`" for f in flags_by_node.get(node, [])) or "—"
        optional = ", ".join(f"`{f}`" for f in optional_flags) if node == "executing" else "—"
        lines.append(f"| `{node}` | `{fn.__name__}` | {required} | {optional} |")

    lines += [
        "",
        "Every `gate-pass` also takes `--by <identity>` and at least one `--artifact <path>` (an empty",
        "list refuses with exit 1; freezing `DRIVE_MAP.md` refuses with exit 2).",
        "",
        "## Exit codes",
        "",
        "| Exit | Meaning |",
        "|---|---|",
        "| `0` | Passed. Artifacts frozen by sha256 and recorded in `gates` and `trail`. The `executing` check also sets `status: live`. |",
        "| `1` | Refused — evidence missing, inconsistent or unreadable. Nothing frozen, nothing recorded. |",
        "| `2` | Usage — an unregistered node, a required evidence flag missing, or `DRIVE_MAP.md` passed as an artifact. |",
        "| `3` | HOLD — `executing` only: a `done` row's verifier run reads `unverifiable` with an undischarged `manual` criterion. Nothing frozen. |",
        "",
        "## What each check reads",
        "",
    ]
    for node, fn in node_gates.CHECKS.items():
        lines += [f"### `{node}` — `{fn.__name__}`", "", _cell(_first_paragraph(fn.__doc__)), ""]

    lines += [
        "## Constants the checks quote",
        "",
        "| Name | Value | Used for |",
        "|---|---|---|",
        f"| `_C10_REFUSAL` | `{_cell(node_gates._C10_REFUSAL)}` | Understand: an all-`manual` criteria set. |",
        f"| `_WHOLE_PATH_REFUSAL` | `{_cell(node_gates._WHOLE_PATH_REFUSAL)}` | Understand: no criterion statement starts `WHOLE-PATH:`. |",
        f"| `_PYDANTIC_MISSING` | `{_cell(node_gates._PYDANTIC_MISSING)}` | Understand: run with an interpreter that lacks the dependencies. |",
        f"| `_COMMITTER_LABEL` | `{node_gates._COMMITTER_LABEL}` | `completed_by` the local verifier writes when it closes a row. |",
        f"| `_CONSOLE_LABEL` | `{node_gates._CONSOLE_LABEL}` | `completed_by` written when a person marks a row done in the console. |",
        f"| `_UPLOADER_LABEL` | `{node_gates._UPLOADER_LABEL}` | A closure door the Build gate refuses by name. |",
        f"| `_LIVE_TEST_DISPOSITION` | `{node_gates._LIVE_TEST_DISPOSITION}` | The only disposition that may cross the Build gate open. |",
        "| `_SKIP_VERIFIER_DISPOSITIONS` | "
        + ", ".join(f"`{d}`" for d in sorted(node_gates._SKIP_VERIFIER_DISPOSITIONS))
        + " | Descoped rows; no verifier run is read for them. |",
        f"| `VERIFICATIONS_SUBDIR` | `{node_gates.VERIFICATIONS_SUBDIR.as_posix()}` | Default `--verifications-dir`, relative to the run folder. |",
        f"| `_RECONCILIATION_LINE` | `{_cell(node_gates._RECONCILIATION_LINE.pattern)}` | One `RECONCILIATION.md` bullet per workplan row. |",
        "",
    ]
    return "\n".join(lines)


# ── status-vocabulary.md ───────────────────────────────────────────────────


def render_status_vocabulary() -> str:
    import loop_terminal

    lines = [
        "# Reference — status vocabulary",
        "",
        GENERATED_NOTE,
        "Source: `bin/loop_terminal.py`. `status` is one of these values; `current_node` never advances",
        "past `executing`.",
        "",
        "| Status | Legitimate ending | Kill trigger |",
        "|---|---|---|",
    ]
    for status in loop_terminal.LOOP_STATUS:
        legit = "yes" if status in loop_terminal.LEGITIMATE_TERMINAL else ""
        kill = "yes — routes to `killed`" if status in loop_terminal.KILL_TRIGGERS else ""
        lines.append(f"| `{status}` | {legit} | {kill} |")
    lines += [
        "",
        "## How the ending is derived",
        "",
        _cell(_first_paragraph(loop_terminal.terminal_route.__doc__)),
        "",
    ]
    return "\n".join(lines)


# ── mcp-tools.md ───────────────────────────────────────────────────────────


def render_mcp_tools() -> str:
    from hyperspace.contracts.candidate import CandidateWorkItem
    from hyperspace.mcp.server import _build_tool_list
    from hyperspace.verify import CompletionClaim

    tools = _build_tool_list()
    schema_sources = {
        "complete_workitem": CompletionClaim.__module__,
        "upsert_work_item": CandidateWorkItem.__module__,
    }
    lines = [
        "# Reference — MCP tools",
        "",
        GENERATED_NOTE,
        "Source: `hyperspace/mcp/server.py` (`_build_tool_list`) over `hyperspace/tools/registry.py`.",
        "The plugin's MCP server is named `hyperspace`; inside a Claude Code session its tools carry the",
        "prefix `mcp__plugin_hyperspace-engine_hyperspace__` (for example",
        "`mcp__plugin_hyperspace-engine_hyperspace__upsert_work_item`). Every tool answers against the",
        "project's `.hyperspace/graph.db`.",
        "",
        "| Tool | What it does |",
        "|---|---|",
    ]
    for tool in tools:
        lines.append(f"| [`{tool.name}`](#{tool.name}) | {_cell(tool.description)} |")
    for tool in tools:
        schema = tool.input_schema or {}
        props = schema.get("properties", {}) or {}
        required = set(schema.get("required", []) or [])
        lines += ["", f"## {tool.name}", "", _cell(tool.description), ""]
        if not props:
            lines.append("No arguments.")
            continue
        lines += ["| Argument | Type | Required |", "|---|---|---|"]
        for name, node in props.items():
            if "anyOf" in node:
                types = " \\| ".join(
                    _json_type(n) if "$ref" not in n else n["$ref"].rsplit("/", 1)[-1] for n in node["anyOf"]
                )
            elif "$ref" in node:
                types = node["$ref"].rsplit("/", 1)[-1]
            elif node.get("type") == "array" and isinstance(node.get("items"), dict):
                item = node["items"]
                inner = item["$ref"].rsplit("/", 1)[-1] if "$ref" in item else _json_type(item)
                types = f"array of {inner}"
            else:
                types = _json_type(node)
            lines.append(f"| `{name}` | {types} | {'yes' if name in required else 'no'} |")
        if "$defs" in schema:
            lines += [
                "",
                "Nested types (" + ", ".join(f"`{d}`" for d in schema["$defs"]) + ") are defined in `"
                + schema_sources.get(tool.name, "hyperspace").replace(".", "/") + ".py`.",
            ]
    lines.append("")
    return "\n".join(lines)


# ── driver ─────────────────────────────────────────────────────────────────

RENDERERS: dict[str, Callable[[], str]] = {
    "state-fields.md": render_state_fields,
    "cli.md": render_cli,
    "gate-contracts.md": render_gate_contracts,
    "status-vocabulary.md": render_status_vocabulary,
    "mcp-tools.md": render_mcp_tools,
}


def render_all() -> dict[str, str]:
    return {name: render() for name, render in RENDERERS.items()}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/reference/*.md from source.")
    parser.add_argument("--check", action="store_true", help="exit 1 if a committed file differs from source")
    args = parser.parse_args(argv)
    drifted = []
    for name, text in render_all().items():
        path = OUT / name
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != text:
                drifted.append(name)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if drifted:
        print("reference drift: " + ", ".join(drifted) + " — run: python docs/reference/generate.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
